import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Ask To The Doc",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ClerkProvider>
          <Provider>{children}</Provider>
          <Toaster />
        </ClerkProvider>
      </body>
    </html>
  );
}
